apiVersion: v2
appVersion: 0.1.2-zarf-support
description: A Helm chart for Kubernetes
name: kelm
type: application
version: 0.1.2-zarf-support

dependencies:
- name: common
  version: 2.x.x
  repository: oci://ghcr.io/riftonix/helm-shared/charts
