image:
  registry: ghcr.io
  repository: riftonix/kelm
  pullPolicy: IfNotPresent
  tag: "0.1.3"

serviceAccount:
  create: true
  annotations: {}
  name: ""

zarf:
  enabled: false
  namespace: zarf

retryDelay: "1h"
watchRetryDelay: "10s"
resyncInterval: "5m"

microservice:
  envs:
    IGNORED_NAMESPACES: >
      default,
      kube-system,
      kube-node-lease,
      kube-public,
      cert-manager

resources: {}
